
===============================
Deploy Nexus repo with Ansible
===============================

first you should create hosts file and put : 
server_ip ansible_ssh_private_key_file=path_of_key ansible_user=server_user
and run configuration with :


.. code-block:: sh

    $ ansible-playbook -i hosts Nexus.yaml
